config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root               'static_pages#home'
  get 'help'      => 'static_pages#help'
  get 'about'     => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'signup'    => 'users#new'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'


  resources :users do
    resources :client_cards, shallow: true
  end    
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client_card.rb
class ClientCard < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  has_many :client_cards, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50 } 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }    
  has_secure_password  
  validates :password, length: { minimum: 6 }, allow_blank: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? 
           BCrypt::Engine::MIN_COST :
           BCrypt::Engine.cost 
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64 
  end 

  def remember
    self.remember_token =  User.new_token 
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil? 
    BCrypt::Password.new(digest).is_password?(token)  
  end

  def forget
    update_attribute(:remember_digest, nil) 
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now) 
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now 
  end

  def create_reset_digest
    self.reset_token = User.new_token 
    update_attribute(:reset_digest, User.digest(reset_token)) 
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now 
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def feed
    ClientCard.where("user_id = ?", id) 
  end

  private

  def downcase_email
    self.email = email.downcase 
  end

  def create_activation_digest
    self.activation_token = User.new_token 
    self.activation_digest = User.digest(activation_token)
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/client_cards_controller.rb
class ClientCardsController < ApplicationController
  before_action :find_user, only: %i[create new index]
  before_action :find_client_card, only: %i[show edit update destroy index]

    rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_client_card_not_found

  # GET /client_cards
  # GET /client_cards.json
  def index
    @client_cards = @user.client_cards.all
  end

  # GET /client_cards/1
  # GET /client_cards/1.json
  def show
  end

  # GET /client_cards/new
  def new
    @client_card = @user.client_cards.new
  end

  # GET /client_cards/1/edit
  def edit
  end

  # POST /client_cards
  # POST /client_cards.json
  def create
    @client_card = @user.client_cards.new(client_card_params)
    if @client_card.save
      redirect_to root_url
    else
      render :new
    end
  end

  # PATCH/PUT /client_cards/1
  # PATCH/PUT /client_cards/1.json
  def update
    respond_to do |format|
      if @client_card.update(client_card_params)
        format.html { redirect_to @client_card, notice: 'Client card was successfully updated.' }
        format.json { render :show, status: :ok, location: @client_card }
      else
        format.html { render :edit }
        format.json { render json: @client_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_cards/1
  # DELETE /client_cards/1.json
  def destroy
    @client_card.destroy
    respond_to do |format|
      format.html { redirect_to client_cards_url, notice: 'Client card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
    def client_card_params
      params.require(:client_card).permit(:title, :user_id, :many, :description, :deadlines, :contract_id, :action_id)
    end
    
    def find_user
      @user = User.find(params[:user_id])
    end

    def find_client_card
      @client_card = ClientCard.find(params[:user_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :set_users
  
  # GET /users
  # GET /users.json
  def index 
    @users = User.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @client_cards = @user.client_cards.paginate(page: params[:page])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        @user.send_activation_email
        redirect_to root_url
      else
        render 'new'
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user.update(user_params)
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy 
    redirect_to users_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    
    def set_users
      @user = User.all
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in." 
        redirect_to login_url
      end
    end
    def correct_user
      @user = User.find(params[:id]) 
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_cards_helper.rb
module ClientCardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase) 
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}" 
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/client_cards/_form.html.erb
<%= form_with model: [:user, @client_card] do |form| %>
  <% if client_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client_card.errors.count, "error") %> prohibited this client_card from being saved:</h2>

      <ul>
      <% client_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :many %>
    <%= form.number_field :many %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :deadlines %>
    <%= form.date_select :deadlines %>
  </div>

  <div class="field">
    <%= form.label :contract_id %>
    <%= form.number_field :contract_id %>
  </div>

  <div class="field">
    <%= form.label :action_id %>
    <%= form.number_field :action_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/client_cards/edit.html.erb
<h1>Editing Client Card</h1>

<%= render 'form', client_card: @client_card %>

<%= link_to 'Show', @client_card %> |
<%= link_to 'Back', client_cards_path %>

app/views/client_cards/index.html.erb
<h1>Client Cards</h1>

<ul class="users">
  <%= render @client_cards %>
</ul>

app/views/client_cards/new.html.erb
<h1>New Client Card</h1>

<%= render 'form', client_card: @client_card %>

<%= link_to 'Back', user_client_cards_path(@user) %>

app/views/client_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @client_card.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @client_card.user_id %>
</p>

<p>
  <strong>Many:</strong>
  <%= @client_card.many %>
</p>

<p>
  <strong>Description:</strong>
  <%= @client_card.description %>
</p>

<p>
  <strong>Deadlines:</strong>
  <%= @client_card.deadlines %>
</p>

<p>
  <strong>Contract:</strong>
  <%= @client_card.contract_id %>
</p>

<p>
  <strong>Action:</strong>
  <%= @client_card.action_id %> 
</p>

<p>
  <strong>Source:</strong>
  <%= @client_card.source_id %> 
</p>

<%= link_to 'Edit', edit_client_card_path(@client_card) %> |
<%= link_to 'Back', client_cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <%= stylesheet_link_tag 'application', media: 'all', 
                                           'data-turbolinks-track' => true %> 
    <%= javascript_include_tag 'application',
                                'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %> 
    <%= render 'layouts/shim' %> 
  </head> 
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>  
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body> 
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password  %>
    <%= form.text_field :password  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %> 
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div> 
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %> 
      <%= render 'shared/error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %> 
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4"> 
  	<section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1> 
    </section>
  </aside> 
  
</div>

<%= link_to 'New Client Card', new_user_client_card_path(@user) %> |
<%= link_to 'All card', user_client_cards_path(@user) %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>